name: App Build

on:
  push:
    branches: [prod, dev]
  pull_request:
    branches: [prod, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Enable android.useAndroidX property
        run: echo 'android.useAndroidX=true' >> gradle.properties

      - name: Build Debug Apk
        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Enable android.useAndroidX property
        run: echo 'android.useAndroidX=true' >> gradle.properties

      - name: Set more jvm memory property
        run: echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties

      - name: Build Debug Apk
        run: ./gradlew test